# -*- coding: utf-8 -*-
"""Exercicio3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cvxaURf4H7pRA1S1uabBm89KYJVb7USg
"""

import math

print('Informe o primeiro valor: ')
valor1 = int(input())
print('Informe o segundo valor:')
valor2 = int(input())
print('Soma: ', valor1+valor2)
print('Diferenca: ', valor1-valor2)
print('Media: ', (valor1+valor2)/2)
print('Distancia: ', math.fabs(valor1-valor2))
print('Maior: ' , (valor1+valor2+math.fabs(valor1-valor2))/2)
print('Menor: ' , (valor1+valor2-math.fabs(valor1-valor2))/2)