# -*- coding: utf-8 -*-
"""Exercicio5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Z69eVKgiYoz8M-M6WsiVSn8-Oh-hlBU
"""

print('Informe o tempo do evento em segundos: ')
tempo = int(input())
horas = tempo//3600
print('Horas:', horas)
resto = tempo%3600
minutos = resto//60
print('Minutos:', minutos)
segundos = resto % 60
print('Segundos: ', segundos)