# -*- coding: utf-8 -*-
"""Exercicio4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PO2bjJEYEt6czx5hNNrwx0VVmsEbPLEw
"""

print('Digite um valor inteiro de 4 digitos:')
valor = int(input())
milhar = valor//1000
resto = valor%1000
centena = resto//100
resto = resto%100
dezena = resto//10
unidade = resto%10
print('Valor invertido: ', unidade*1000 + dezena*100 + centena*10 + milhar)