# -*- coding: utf-8 -*-
"""Exercicio1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K87wGgdVcYpQA-zPB_iH9kxr3KpQI4L6
"""

print('Informe um valor: ')
valor = float(input())
print('Quadrado do valor =', valor**2)
print('Cubo do valor = ', valor ** 3)
print('Valor na quarta = ', valor ** 4)