# -*- coding: utf-8 -*-
"""Exercicio2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eSWT_wRBQuDatCmyshrLFj3TRYqxWwp6
"""

print('Informe o valor em farenheit:')
f = float(input())
c = 5/9 * (f-32)
print('Celsius:', c)