# -*- coding: utf-8 -*-
"""volumeDaEsfera.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YuOyreVwBRylwi05hEdxF3zrSsGtsa7S
"""

import math
print('Informe o valor do raio:')
raio = float(input())
volume = 4/3 * math.pi * math.pow(raio,3)
print('Volume: ', volume)