# -*- coding: utf-8 -*-
"""volumeDeEsfera2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v9FfCi4jqeUfjxd_KM6JWLBG5GdY5jJP
"""

import math

print('Informe o valor do raio:')
raio = float(input())
area = 4 * math.pi * raio**2
print('Area da esfera: ', area)

